name: Frontend CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "src-tauri/**"
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "src-tauri/**"
      - "README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  lint-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: SvelteKit sync
        env:
          PUBLIC_API_URL: "https://starlight.allofus.dev"
        run: bunx svelte-kit sync

      - name: Run Lint
        run: bun run lint

      - name: Run Check
        env:
          PUBLIC_API_URL: "https://starlight.allofus.dev"
        run: bun run check
